### PR TITLE
Update to latest valetudo-mapper

### PR DESCRIPTION
**Pull request by gerard33**
Update to latest valetudo-mapper which contains some [fixes](https://github.com/rand256/valetudo-mapper/commit/426718f5e037b5a4118a2ec154645e3966820a5b) for the new Home Assistant MQTT format.
It should fix the following warning which gets deprecated in 2024.2 release.

`
MQTT entity name starts with the device name in your config {'name': 'rockrobo_map', 'unique_id': 'rockrobo_map', 'device': {'manufacturer': 'Roborock', 'name': 'rockrobo', 'identifiers': ['rockrobo'], 'connections': []}, 'topic': 'valetudo/rockrobo/map', 'availability_mode': 'latest', 'payload_not_available': 'offline', 'encoding': 'utf-8', 'qos': 0, 'enabled_by_default': True, 'payload_available': 'online'}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes '_map'
`

### CODE REVIEW

**Review by Poeschl — CHANGES_REQUESTED** [review]
This will dynamically always use the master branch instead of a fixed version.
This need to be changed to the latest commit hash, if no tag can be used.

**Comment by gerard33** [comment]
Changed it to the latest commit. Do you expect any issues when using the latest version on master?

**Comment by Poeschl** [comment]
When using master, the container content is not fixed. So the same build can produce different outputs on two different dates.
Therefore I pin all versions.

**Comment by gerard33** [comment]
@Poeschl can you have a look at this PR? The current format gets deprecated in the next Home Assistant release.

**Review by Poeschl — APPROVED** [review]
Thanks for the reminder, the changes looks good now.

I will make some time this week to go over the PRs.

**Pull request merged**
