### PR TITLE
[git-exporter] Allow customising secret patterns

### PR DESCRIPTION
**Pull request by bjeanes**
Addresses #314

I haven't been able to test this on my existing install because I am not sure if it's possible to add an add-on repository from non-default branch and changing repo metadata would pollute this PR.

### CODE REVIEW

**Comment by Poeschl** [comment]
Addons can be tested locally with the folder inside the `/addons` mount point. Just remove the `image: ` from the config.json and your HA Host will build it locally. The addon will appear in the Store as "Local addon". ;) That's how I test new addons most of the time.

**Comment by bjeanes** [comment]
Yeah I tried that but was getting a Docker build error. I think perhaps some of the apk packages you had version-pinned have bumped versions and they still pass here because your GH Actions have that layer cached. At least, that was my theory...

**Comment by Poeschl** [comment]
@bjeanes They, don't pass 😅
alpine Linux simply replace all old versions when a new one is available for some reason....
So for working correctly the git package must be updated I think

**Comment by bjeanes** [comment]
Yup. I created a `testing` branch in my fork where I just removed all the version requirements haha. In my own repos I don't pin Alpine package versions for exactly this reason. I just rely on the immutability of Docker layers!

**Comment by Poeschl** [comment]
Shh bot, no time to review, but not stale 😅

**Pull request merged**
