### PR TITLE
Tune README.md and default configs for Valetudo add-ons

### PR DESCRIPTION
**Pull request by shalak**

### CODE REVIEW

**Comment by Poeschl** [comment]
Are the topics the same for valetudo-mapper?

**Comment by shalak** [comment]
> Are the topics the same for valetudo-mapper?

Huh, now that you mentioned it - I'm not entirely sure. As far as I understand, valetudo-mapper is basically a fork of  ICantBelieveItsNotValetudo, but used for the Valetudo RE firmware, right? Since I didn't verify it, I'll remove changes related to it.

**Comment by Poeschl** [comment]
Looks good.
Could you also increase the addon version in the minor place in config.json and write a line for this in the Changelog? Then it will be merged and deployed right away.

**Review by Poeschl — APPROVED** [review]
Looks good. Thanks for contributing 😃 👍

**Pull request merged**
