### PR TITLE
syncthing/DOCS.md: Improve Configuration section

### PR DESCRIPTION
**Pull request by reedy**
Part of https://github.com/Poeschl/Hassio-Addons/issues/415

### CODE REVIEW

**Review by salim-b — CHANGES_REQUESTED** [review]
I'd suggest to change the line to:

```
Configuration is done via [Syncthing's web UI](https://my.home-assistant.io/redirect/supervisor_ingress/?addon=243ffc37_syncthing) (embedded into Home Assistant). First start the add-on from the [*Info* tab](https://my.home-assistant.io/redirect/supervisor_addon/?addon=243ffc37_syncthing) and then click <kbd>OPEN WEB UI</kbd>.
```

which should render to

> Configuration is done via [Syncthing's web UI](https://my.home-assistant.io/redirect/supervisor_ingress/?addon=243ffc37_syncthing) (embedded into Home Assistant). First start the add-on from the [*Info* tab](https://my.home-assistant.io/redirect/supervisor_addon/?addon=243ffc37_syncthing) and then click <kbd>OPEN WEB UI</kbd>.

**Comment by reedy** [comment]
> I'd suggest to change the line to:
> 
> ```
> Configuration is done via [Syncthing's web UI](https://my.home-assistant.io/redirect/supervisor_ingress/?addon=243ffc37_syncthing) (embedded into Home Assistant). First start the add-on from the [*Info* tab](https://my.home-assistant.io/redirect/supervisor_addon/?addon=243ffc37_syncthing) and then click <kbd>OPEN WEB UI</kbd>.
> ```
> 
> which should render to
> 
> > Configuration is done via [Syncthing's web UI](https://my.home-assistant.io/redirect/supervisor_ingress/?addon=243ffc37_syncthing) (embedded into Home Assistant). First start the add-on from the [_Info_ tab](https://my.home-assistant.io/redirect/supervisor_addon/?addon=243ffc37_syncthing) and then click OPEN WEB UI.

Thanks!

It seems... a bit excessive to use a redirect via an external service in this case.

Going from what is probably being viewed locally on a HA instance anyway (purpose of DOCS.md), via the internet and back to an adjacent page...

Is this a pattern that's actually done in other places? It feels like something that should be doable locally too, but I can't find any useful docs though for it...

**Comment by reedy** [comment]
We can do stuff like `/hassio/dashboard`, which will work in most cases, unless people have "non standard" configs (where they may have things under extra subdirs)...

**Comment by salim-b** [comment]
> It seems... a bit excessive to use a redirect via an external service in this case.

Fair point.

> Going from what is probably being viewed locally on a HA instance anyway (purpose of DOCS.md), via the internet and back to an adjacent page...

We could simply use `/hassio/addon/243ffc37_syncthing/info` and `/hassio/ingress/243ffc37_syncthing` as the link targets. The main advantage of using the external my.home-assistant.io service in that case is that if a future version of HA happens to use different paths, the links will continue to work.

**Comment by reedy** [comment]
It's not the end of the world either way, I'm sure you can always find someone it's broken for...

We could do something like...

```
Configuration is done via [Syncthing's web UI](/hassio/ingress/243ffc37_syncthing) (embedded into Home Assistant). First start the add-on from the [*Info* tab](/hassio/addon/243ffc37_syncthing/info) and then click <kbd>OPEN WEB UI</kbd>.

If these links don't work for you, you can try the `my.home-assistant.io` service:
* [Syncthing's web UI](https://my.home-assistant.io/redirect/supervisor_ingress/?addon=243ffc37_syncthing
* https://my.home-assistant.io/redirect/supervisor_addon/?addon=243ffc37_syncthing
```

>Configuration is done via [Syncthing's web UI](/hassio/ingress/243ffc37_syncthing) (embedded into Home Assistant). First start the add-on from the [*Info* tab](/hassio/addon/243ffc37_syncthing/info) and then click <kbd>OPEN WEB UI</kbd>.
>
>If these links don't work for you, you can try the `my.home-assistant.io` service:
>* [Syncthing's web UI](https://my.home-assistant.io/redirect/supervisor_ingress/?addon=243ffc37_syncthing
>* https://my.home-assistant.io/redirect/supervisor_addon/?addon=243ffc37_syncthing

Don't need perfection, and most things are arguably better than what is there now :)

**Comment by salim-b** [comment]
I think it's fine to just use the direct links. The additional paragraph "If these links don't work for you, ..." is a bit overkill... 😄

**Pull request closed without merging**
